function Part(){
	this._url=window.location.href;
	this._identify=this._url.match(/n=\d+/g)[0].replace(/n=/g,"");
	this.mains=document.getElementById("main");
	this.img1=null;
	this.img2=null;
	this.div=null;
	this.div2=null;
	this.a=null;
	var _this=this;
	this.parts=function(){
		//console.log(_this._identify)
		$.get("js/mainzt.json",null,function(data,textStatus){
			if(textStatus="success"){
				//console.log(data["img"+_this._identify])
				//console.log(JSON.stringify(data["img"+_this._identify]).split(",").length)
				_this.idefy=JSON.stringify(data["img"+_this._identify]).split(",").length;
				_this.div=document.createElement("div");
				_this.div.className="mainHead";
				_this.div.style.backgroundImage="url("+data["img"+_this._identify]["src0"]+")";
				_this.mains.appendChild(_this.div);
				_this.div2=document.createElement("div");
				_this.div2.className="mainbottom";
				_this.mains.appendChild(_this.div2);
				_this.mains.style.backgroundColor=data["img"+_this._identify]["bj"];
				for(_this.i=0;_this.i<_this.idefy;_this.i++){
					_this.a=document.createElement("a");
					_this.a.href="shoping.html?n=10"+_this._identify+_this.i;
					_this.a.target="_blank";
					_this.div2.appendChild(_this.a);
					_this.img2=document.createElement("img");
					_this.img2.src=data["img"+_this._identify]["src"+(_this.i+1)];
					_this.a.appendChild(_this.img2);
				}
			}
		},"json")
	}
}
